owms:
  tenant: ZILE
  driver:
    connections:
      hostname: localhost
      identified-by-field: "osip_sender"
      subsystems:
        - name: SPS01
          inbound:
            mode: server
            port: 30001
          outbound:
            mode: server
            port: 31001
            identified-by-value: "SPS01"
        - name: SPS04
          duplex:
            mode: server
            port: 30004
            identified-by-value: "SPS04"
        - name: SPS05
          duplex:
            mode: client
            port: 30005
            identified-by-value: "SPS05"
