apiVersion: apps/v1
kind: Deployment
metadata:
  name: owms-config
  labels:
    app: owms-config
spec:
  replicas: 1
  selector:
    matchLabels:
      app: owms-config
  template:
    metadata:
      labels:
        app: owms-config
    spec:
      containers:
        - name: config-server
          image: interface21/openwms-configuration:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8099
          env:
            - name: owms_eureka_url
              value: http://user:sa@owms-services:8761
---
apiVersion: v1
kind: Service
metadata:
  name: owms-config
spec:
  ports:
  - port: 8099
  selector:
    app: owms-config