apiVersion: apps/v1
kind: Deployment
metadata:
  name: oleap-config
  labels:
    app: oleap-config
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oleap-config
  template:
    metadata:
      labels:
        app: oleap-config
    spec:
      containers:
        - name: config-server
          image: openleap/openleap-config:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8099
          env:
            - name: oleap_eureka_url
              value: http://user:sa@oleap-services:8761
---
apiVersion: v1
kind: Service
metadata:
  name: oleap-config
spec:
  ports:
  - port: 8099
  selector:
    app: oleap-config