apiVersion: v1
kind: Service
metadata:
  name: oleap-config
  labels:
    app: oleap-config
spec:
  type: LoadBalancer
  ports:
  - port: 8099
    protocol: TCP
    targetPort: 8099
  selector:
    app: oleap-config
