server:
  port: ${PORT:8099}

spring:
  profiles:
   active: ${SPRING_PROFILES_ACTIVE:native}
  application:
    name: openleap-config
  security:
    user:
      name: ${REGISTRY_USER:user}
      password: ${REGISTRY_PASSWORD:sa}
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_GIT_URL:git@github.com:openleap-io/io.openleap.config-repo.git}
          force-pull: true
          search-paths: ${CONFIG_SEARCH_PATH:config}
          clone-on-start: true
          username: ${CONFIG_SSH_USERNAME:your_username}
          password: ${CONFIG_SSH_PASSWORD:your_password}
          default-label: main
encrypt:
  keyStore:
    location: ${CONFIG_KEY_STORE_LOCATION:classpath:/server.jks}
    password: ${CONFIG_KEY_STORE_PASSWORD:letmein}
    alias: ${CONFIG_KEY_STORE_ALIAS:mytestkey}
    secret: ${CONFIG_KEY_STORE_SECRET:letmein}

health:
  config:
    enabled: true

oleap:
  eureka:
    url: ${oleap.srv.protocol}://${spring.security.user.name}:${spring.security.user.password}@${oleap.srv.hostname}:${oleap.srv.port}
    zone: ${oleap.eureka.url}/eureka/
  srv:
    protocol: ${REGISTRY_PROTOCOL:http}
    hostname: ${REGISTRY_HOSTNAME:localhost}
    port: ${REGISTRY_PORT:8761}

eureka:
  client:
    healthcheck:
      enabled: true
    instance-info-replication-interval-seconds: 10 # default is 30
    service-url:
      defaultZone: ${oleap.eureka.zone} # Must be camelCase
  instance:
    hostname: ${oleap.srv.hostname}
    secure-port-enabled: false
    non-secure-port-enabled: true
    metadata-map:
      username: ${spring.security.user.name}
      password: ${spring.security.user.password}
      protocol: ${oleap.srv.protocol}
      zone: ${oleap.eureka.zone}

management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  file:
    name: BOOT-CORE-Config.log
    path: "/tmp/oleap"

---
spring:
  config:
    activate:
      on-profile: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:config/
        bootstrap: true
