spring:
  application:
    name: openleap-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/openleap-io/io.openleap.config
          search-paths: conf
          clone-on-start: true
          default-label: master
  security:
    user:
      password: sa
      name: user

health:
  config:
    enabled: true

oleap:
  eureka:
    url: http://user:sa@localhost:8761
    zone: ${oleap.eureka.url}/eureka/
  srv:
    protocol: http
    hostname: localhost

server:
  port: ${PORT:8099}

eureka:
  client:
    healthcheck:
      enabled: true
    instance-info-replication-interval-seconds: 10 # default is 30
    service-url:
      defaultZone: ${oleap.eureka.zone} # Must be camelCase
  instance:
    hostname: ${oleap.srv.hostname}
    secure-port-enabled: false
    non-secure-port-enabled: true
    metadata-map:
      username: ${spring.security.user.name}
      password: ${spring.security.user.password}
      protocol: ${oleap.srv.protocol}
      zone: ${oleap.eureka.zone}

management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  file:
    name: BOOT-CORE-Config.log
    path: "/tmp/oleap"

---
spring:
  config:
    activate:
      on-profile: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:config/
        bootstrap: true
