branch-defaults:
  master:
    environment: openwms-configuration-DEVELOPMENT
environment-defaults:
  Team4PbghArchaius-env:
    branch: null
    repository: null
global:
  application_name: openwms-configuration
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:eu-central-1::platform/Java 8 running
    on 64bit Amazon Linux/2.8.3
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
