version: 0.0
os: linux
files:
  - source: ./
    destination: /home/ubuntu/app/archaius

permissions:
  - object: /home/ubuntu/app/archaius
    pattern: "*.sh"
    owner: root
    group: root
    mode: 755

hooks:
  ApplicationStart:
    - location: runapp.sh
      timeout: 300
      runas: root
